//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinearCalibration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LinearCalibration()
        {
            this.CalibrationData = new HashSet<DataPoint>();
            this.SaltAnalysis = new HashSet<SaltAnalysisData>();
        }
    
        public int IDCalibration { get; set; }
        public System.DateTime Date { get; set; }
        public string Comment { get; set; }
        public string CalibrationType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataPoint> CalibrationData { get; set; }
        public virtual CalibrationType CalibrationTypeSelector { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaltAnalysisData> SaltAnalysis { get; set; }
    }
}
