//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;
using Samples;
namespace SA_EF
{  
    public partial class ChemicalAnalysesEntities : DbContext
    {
        public ChemicalAnalysesEntities()
            : base("name=ChemicalAnalysesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calibration> Calibration { get; set; }
        public virtual DbSet<CalibrationData> CalibrationData { get; set; }
        public virtual DbSet<SaltAnalysisData> SaltAnalysis { get; set; }
        public virtual DbSet<Sample> Sample { get; set; }
        public virtual DbSet<CalibrationType> CalibrationType { get; set; }
        public virtual DbSet<CalibrationDataView> CalibrationDataView { get; set; }
        public virtual DbSet<SaltAnalysisView> SaltAnalysisView { get; set; }
        public virtual DbSet<SamplesView> SamplesView { get; set; }
    
        public virtual int GetSamplesByMultipleIDs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetSamplesByMultipleIDs");
        }
    
        public virtual int UpdateCalibrationData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCalibrationData");
        }
    }
}
