//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using SaltAnalysisDatas;
using System.Diagnostics.CodeAnalysis;

namespace SA_EF
{
    public partial class Sample
    {
        [SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sample()
        {
            this.SaltAnalysis = new HashSet<SaltAnalysisData>();
        }
    
        public int IDSample { get; set; }
        public string LabNumber { get; set; }
        public DateTime SamplingDate { get; set; }
        public string Description { get; set; }
        public string Comment { get; set; }
    
        [SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaltAnalysisData> SaltAnalysis { get; set; }
    }
}
