//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SamplesView
    {
        public int IDSample { get; set; }
        public string LabNumber { get; set; }
        public System.DateTime SamplingDate { get; set; }
        public string Description { get; set; }
        public Nullable<int> SamplesCount { get; set; }
    }
}
