//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemicalAnalyses.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22.989768")]
        public decimal Na {
            get {
                return ((decimal)(this["Na"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("39.0983")]
        public decimal K {
            get {
                return ((decimal)(this["K"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35.4527")]
        public decimal Cl {
            get {
                return ((decimal)(this["Cl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40.078")]
        public decimal Ca {
            get {
                return ((decimal)(this["Ca"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24.305")]
        public decimal Mg {
            get {
                return ((decimal)(this["Mg"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12.0107")]
        public decimal C {
            get {
                return ((decimal)(this["C"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15.9994")]
        public decimal O {
            get {
                return ((decimal)(this["O"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.00794")]
        public decimal H {
            get {
                return ((decimal)(this["H"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32.066")]
        public decimal S {
            get {
                return ((decimal)(this["S"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("79.904")]
        public decimal Br {
            get {
                return ((decimal)(this["Br"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.811")]
        public decimal B {
            get {
                return ((decimal)(this["B"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0008")]
        public decimal CarnalliteThreshold {
            get {
                return ((decimal)(this["CarnalliteThreshold"]));
            }
            set {
                this["CarnalliteThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal HgCoefficient {
            get {
                return ((decimal)(this["HgCoefficient"]));
            }
            set {
                this["HgCoefficient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9.65")]
        public decimal BrBlank {
            get {
                return ((decimal)(this["BrBlank"]));
            }
            set {
                this["BrBlank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1332")]
        public decimal BrTitre {
            get {
                return ((decimal)(this["BrTitre"]));
            }
            set {
                this["BrTitre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.008")]
        public decimal SulfatesBlank {
            get {
                return ((decimal)(this["SulfatesBlank"]));
            }
            set {
                this["SulfatesBlank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0782")]
        public decimal CaTrilonB {
            get {
                return ((decimal)(this["CaTrilonB"]));
            }
            set {
                this["CaTrilonB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0782")]
        public decimal MgTrilonB {
            get {
                return ((decimal)(this["MgTrilonB"]));
            }
            set {
                this["MgTrilonB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("e:\\non_existing file.mdb")]
        public string DBFilePath {
            get {
                return ((string)(this["DBFilePath"]));
            }
            set {
                this["DBFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CA.log")]
        public string LogFile {
            get {
                return ((string)(this["LogFile"]));
            }
            set {
                this["LogFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::ChemicalAnalyses.Alumni.SampleFilterFields PreviousFilter {
            get {
                return ((global::ChemicalAnalyses.Alumni.SampleFilterFields)(this["PreviousFilter"]));
            }
            set {
                this["PreviousFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int KaliumCalibrationNumber {
            get {
                return ((int)(this["KaliumCalibrationNumber"]));
            }
            set {
                this["KaliumCalibrationNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int NatriumCalibrationNumber {
            get {
                return ((int)(this["NatriumCalibrationNumber"]));
            }
            set {
                this["NatriumCalibrationNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.005")]
        public decimal SumTolerance {
            get {
                return ((decimal)(this["SumTolerance"]));
            }
            set {
                this["SumTolerance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True\r\n0,005\r\nCaSO4;0,005;Na;0,005;CrystWater;0,005;NaCl;0,005;KCl;0,005;CaCl2;0,0" +
            "05;MgCl2;0,005;KBr;0,005;HygroWater;0,005;IonSum;0,005;SaltSum;0,005;MgDry;0,005" +
            ";CaDry;0,005;ClDry;0,005;BrDry;0,005;ResiduumDry;0,005;SulfatesDry;0,005;KDry;0," +
            "005")]
        public string Chloride_SchemeToleranceValues {
            get {
                return ((string)(this["Chloride_SchemeToleranceValues"]));
            }
            set {
                this["Chloride_SchemeToleranceValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True\r\n0,005\r\nCaSO4;0,005;Na;0,005;CrystWater;0,005;NaCl;0,005;KCl;0,005;HygroWate" +
            "r;0,005;MgSO4;0,005;Na2SO4;0,005;NaBr;0,005;IonSum;0,005;SaltSum;0,005;MgDry;0,0" +
            "05;CaDry;0,005;ClDry;0,005;BrDry;0,005;ResiduumDry;0,005;SulfatesDry;0,005;KDry;" +
            "0,005")]
        public string SulfateSodiumI_SchemeToleranceValues {
            get {
                return ((string)(this["SulfateSodiumI_SchemeToleranceValues"]));
            }
            set {
                this["SulfateSodiumI_SchemeToleranceValues"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True\r\n0,005\r\nCaSO4;0,005;Na;0,005;CrystWater;0,005;NaCl;0,005;KCl;0,005;MgCl2;0,0" +
            "05;HygroWater;0,005;MgSO4;0,005;NaBr;0,005;IonSum;0,005;SaltSum;0,005;MgDry;0,00" +
            "5;CaDry;0,005;ClDry;0,005;BrDry;0,005;ResiduumDry;0,005;SulfatesDry;0,005;KDry;0" +
            ",005")]
        public string SulfateMagnesiumI_SchemeToleranceValues {
            get {
                return ((string)(this["SulfateMagnesiumI_SchemeToleranceValues"]));
            }
            set {
                this["SulfateMagnesiumI_SchemeToleranceValues"] = value;
            }
        }
    }
}
