//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaltAnalysisDatas.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class SADatas : global::System.Configuration.ApplicationSettingsBase {
        
        private static SADatas defaultInstance = ((SADatas)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SADatas())));
        
        public static SADatas Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NaTestCalibration.xml")]
        public string NatirumCalibrationFile {
            get {
                return ((string)(this["NatirumCalibrationFile"]));
            }
            set {
                this["NatirumCalibrationFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("KTestCalibration.xml")]
        public string KaliumCalibrationFile {
            get {
                return ((string)(this["KaliumCalibrationFile"]));
            }
            set {
                this["KaliumCalibrationFile"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\mssqllocaldb;AttachDbFilename=E:\\IIT\\Projects\\СВПП\\KSR\\Chem" +
            "icalAnalyses\\ChemicalAnalyses.mdf;Initial Catalog=ChemicalAnalyses;Integrated Se" +
            "curity=True")]
        public string ChemAnConnectionString {
            get {
                return ((string)(this["ChemAnConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22.99")]
        public decimal Na {
            get {
                return ((decimal)(this["Na"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("39.098")]
        public decimal K {
            get {
                return ((decimal)(this["K"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35.45")]
        public decimal Cl {
            get {
                return ((decimal)(this["Cl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40.078")]
        public decimal Ca {
            get {
                return ((decimal)(this["Ca"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24.305")]
        public decimal Mg {
            get {
                return ((decimal)(this["Mg"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12.011")]
        public decimal C {
            get {
                return ((decimal)(this["C"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15.999")]
        public decimal O {
            get {
                return ((decimal)(this["O"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.008")]
        public decimal H {
            get {
                return ((decimal)(this["H"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32.06")]
        public decimal S {
            get {
                return ((decimal)(this["S"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("79.904")]
        public decimal Br {
            get {
                return ((decimal)(this["Br"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.81")]
        public decimal B {
            get {
                return ((decimal)(this["B"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.0008")]
        public decimal CarnalliteThreshold {
            get {
                return ((decimal)(this["CarnalliteThreshold"]));
            }
            set {
                this["CarnalliteThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public decimal HgCoefficient {
            get {
                return ((decimal)(this["HgCoefficient"]));
            }
            set {
                this["HgCoefficient"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9.65")]
        public decimal BrBlank {
            get {
                return ((decimal)(this["BrBlank"]));
            }
            set {
                this["BrBlank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1332")]
        public decimal BrTitre {
            get {
                return ((decimal)(this["BrTitre"]));
            }
            set {
                this["BrTitre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal SulfatesBlank {
            get {
                return ((decimal)(this["SulfatesBlank"]));
            }
            set {
                this["SulfatesBlank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0782")]
        public decimal CaTrilonB {
            get {
                return ((decimal)(this["CaTrilonB"]));
            }
            set {
                this["CaTrilonB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.0782")]
        public decimal MgTrilonB {
            get {
                return ((decimal)(this["MgTrilonB"]));
            }
            set {
                this["MgTrilonB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int KaliumCalibrationNumber {
            get {
                return ((int)(this["KaliumCalibrationNumber"]));
            }
            set {
                this["KaliumCalibrationNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NatriumCalibrationNumber {
            get {
                return ((int)(this["NatriumCalibrationNumber"]));
            }
            set {
                this["NatriumCalibrationNumber"] = value;
            }
        }
    }
}
